# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import media_pb2 as media__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadProfilePicture = channel.unary_unary(
                '/media.MediaService/UploadProfilePicture',
                request_serializer=media__pb2.UploadProfilePictureRequest.SerializeToString,
                response_deserializer=media__pb2.UploadMediaResponse.FromString,
                _registered_method=True)
        self.RemoveProfilePicture = channel.unary_unary(
                '/media.MediaService/RemoveProfilePicture',
                request_serializer=media__pb2.RemoveProfilePictureRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UploadProductImage = channel.unary_unary(
                '/media.MediaService/UploadProductImage',
                request_serializer=media__pb2.UploadProductImageRequest.SerializeToString,
                response_deserializer=media__pb2.UploadMediaResponse.FromString,
                _registered_method=True)
        self.RemoveProductImage = channel.unary_unary(
                '/media.MediaService/RemoveProductImage',
                request_serializer=media__pb2.RemoveProductImageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveProfilePictureMeta = channel.unary_unary(
                '/media.MediaService/SaveProfilePictureMeta',
                request_serializer=media__pb2.ProfilePictureMetaRequest.SerializeToString,
                response_deserializer=media__pb2.UploadMediaResponse.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadProfilePicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProfilePicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadProductImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProductImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProfilePictureMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadProfilePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadProfilePicture,
                    request_deserializer=media__pb2.UploadProfilePictureRequest.FromString,
                    response_serializer=media__pb2.UploadMediaResponse.SerializeToString,
            ),
            'RemoveProfilePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProfilePicture,
                    request_deserializer=media__pb2.RemoveProfilePictureRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UploadProductImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadProductImage,
                    request_deserializer=media__pb2.UploadProductImageRequest.FromString,
                    response_serializer=media__pb2.UploadMediaResponse.SerializeToString,
            ),
            'RemoveProductImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProductImage,
                    request_deserializer=media__pb2.RemoveProductImageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveProfilePictureMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProfilePictureMeta,
                    request_deserializer=media__pb2.ProfilePictureMetaRequest.FromString,
                    response_serializer=media__pb2.UploadMediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'media.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('media.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadProfilePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/UploadProfilePicture',
            media__pb2.UploadProfilePictureRequest.SerializeToString,
            media__pb2.UploadMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProfilePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/RemoveProfilePicture',
            media__pb2.RemoveProfilePictureRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadProductImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/UploadProductImage',
            media__pb2.UploadProductImageRequest.SerializeToString,
            media__pb2.UploadMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProductImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/RemoveProductImage',
            media__pb2.RemoveProductImageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveProfilePictureMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaService/SaveProfilePictureMeta',
            media__pb2.ProfilePictureMetaRequest.SerializeToString,
            media__pb2.UploadMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
